DEFAULT_CONFIG = "default-config.yaml"

CONFIG_FILE = "norm.yaml"

_NORM_LINK = "https://github.com/devfros/nORM"

MODULE_COMMENT = f"""
Generated by nORM. READ ONLY.
{_NORM_LINK}
"""

OPTIONAL_PREFIX = "_"

TEMP_PLACEHOLDER_PATTERN = "/*{}*/"

SUPPORTED_SQL_DIALECTS = frozenset(
    {"postgres", "sqlite", "mysql", "clickhouse", "duckdb"}
)
SUPPORTED_PYTHON_MODELS = frozenset({"pydantic", "dataclasses"})

# Connection schemes accepted while postgres is the only supported engine.
SUPPORTED_POSTGRES_CONNECTION_SCHEMES = frozenset({"postgres", "postgresql"})
